export { default as About } from "./About/About";
export { default as Contact } from "./Contact/Contact";
export { default as Dashboard } from "./Dashboard/Dashboard";
export { default as Extension } from "./Extension/Extension";
export { default as Main } from "./Main/Main";
export { default as Navigation } from "./Navigation/Navigation";
export { default as SignIn } from "./SignIn/SignIn";
export { default as SignUp } from "./SignUp/SignUp";
export { default as WishList } from "./WishList/WishList";
