name: Tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.8.0
          check-latest: true

      - name: Get latest NPM version
        run: npm install npm@latest

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
